### ISSUE TITLE
Define strategy of versioning

### ISSUE THREAD

**Issue by jraska** [jraska/github-client#236]
- How to automatically update version?
- How to bump major/minor etc.
- One option is using the tag

**Comment by lordcodes** [comment]
I have a set of Gradle tasks: prepareRelease[Major|Minor|Patch]. They increment the appropriate part of the version stored in a Kotlin file in buildSrc. They also need to set lower parts of version to 0.

Increment minor from 0.1.2 goes to 0.2.0 for example.

To perform a release, I then have a Gradle task which uses the version in that file to create a Git tag. CI has a workflow that is triggered by Git tag and does a release to Google Play internal channel.

The release workflow uses Gradle tasks inside the project to do each part, so that if I really needed to (issues with CI) I would do all the release locally (provided I put the secrets where they needed to be).

My release workflow also does other things that are needed such as creating Jira release, adding that to all the tickets contained in the release, marking it as released, then posting all the Jira task names and IDs as release notes message to a Slack channel.

I found it very interesting putting it all together! Will happily show you what I have sometime, if you are interested.

**Comment by jraska** [comment]
Yes I'm definitely interested! Thanks a lot for the notes :)

I tried to think about the requirements I have:
1. Complete release to Google Play and all other things like Jira should happen by executing single task - `publishRelease`
2. It should be executable both from local environment and CI, also needs to be able to trigger manually on CI
3. It should be clear in git which version a commit points to.
4. Possibly 100% of all logic in Gradle
5. The only manual action should be promoting to Beta and staged rollout. - These could be automated as well.
6. As trivial strategy as possible.

One thing related to 3. is if the CI needs to modify anything in VCS or not? Because I was thinking about variants on how to avoid this.

The thing is where this version number should be - one options is the version number in file as you mention, other one we used in the past is having the latest git tag as this reference and push the next tag based on this. We can discuss that as well :)

**Comment by jraska** [comment]
![Automatic release](https://user-images.githubusercontent.com/6277721/111708033-66939100-8845-11eb-8643-439ff47d05ba.png)

Will try this with GitHub actions :)

**Comment by lordcodes** [comment]
This is exactly what I do right now for GetBusy.

**Comment by jraska** [comment]
@lordcodes do you use Milestones or can't we somehow provide backward reference into each PR to release directly? The Milestone feels like a patch of this not being possible :)

**Comment by lordcodes** [comment]
We use Jira so all done on there for now.

**Comment by jraska** [comment]
Ah ok :) thanks

**Comment by jraska** [comment]
Resolved by #445 

Example release: https://github.com/jraska/github-client/releases/tag/0.24.0
<img width="1271" alt="Screenshot 2021-03-21 at 21 55 58" src="https://user-images.githubusercontent.com/6277721/111920626-486da100-8a90-11eb-9b21-d0042df8151b.png">

Version is bumped for following release: example automatic commit: https://github.com/jraska/github-client/commit/88c0d9a7240be6dab8646d14a9ffa13682e07ae6
<img width="1278" alt="Screenshot 2021-03-21 at 21 51 43" src="https://user-images.githubusercontent.com/6277721/111920512-b5cd0200-8a8f-11eb-8c61-4adec540fa11.png">
